DROP TABLE RATTACHMENT;
DROP TABLE REPORT;
DROP TABLE WISH;
DROP TABLE EATTACHMENT;
DROP TABLE EVENT;
DROP TABLE NATTACHMENT;
DROP TABLE NOTICE;
DROP TABLE IATTACHMENT;
DROP TABLE INREVIEW;
DROP TABLE CHAT_LOG;
DROP TABLE CHAT_LIST;
DROP TABLE REGION;
DROP TABLE PAYMENT;
DROP TABLE RESERVATION;
DROP TABLE PHOTO;
DROP TABLE HOUSE;
DROP TABLE FATTACHMENT;
DROP TABLE FIND_REPLY;
DROP TABLE FIND;
DROP TABLE BATTACHMENT;
DROP TABLE BOARD_REPLY;
DROP TABLE BOARD;
DROP TABLE MEMBER_AUTH;
DROP TABLE MEMBER;

DROP SEQUENCE SEQ_NAT_NO;
DROP SEQUENCE SEQ_NOTICE_NO;
DROP SEQUENCE SEQ_EVENT_NO;
DROP SEQUENCE SEQ_EAT_NO;

DROP SEQUENCE SEQ_CNO;
DROP SEQUENCE SEQ_INR;
DROP SEQUENCE SEQ_IA;

DROP SEQUENCE SEQ_HOUSE_NO;
DROP SEQUENCE SEQ_PHOTO_NO;
DROP SEQUENCE SEQ_REZ_NO;
DROP SEQUENCE SEQ_REGION_NO;

DROP SEQUENCE SEQ_REPORT_NO;
DROP SEQUENCE SEQ_RAT_NO;

DROP SEQUENCE SEQ_BNO;
DROP SEQUENCE SEQ_BRE_NO;
DROP SEQUENCE SEQ_BAT_NO;

DROP SEQUENCE SEQ_FIND_NO;
DROP SEQUENCE SEQ_FIND_REPLY_NO;
DROP SEQUENCE SEQ_FATTACHMENT_NO;

DROP SEQUENCE SEQ_PAYMENT_NO;


CREATE SEQUENCE SEQ_NOTICE_NO NOCACHE;
CREATE SEQUENCE SEQ_NAT_NO NOCACHE;
CREATE SEQUENCE SEQ_EVENT_NO NOCACHE;
CREATE SEQUENCE SEQ_EAT_NO NOCACHE;

CREATE SEQUENCE SEQ_CNO NOCACHE;
CREATE SEQUENCE SEQ_INR NOCACHE;
CREATE SEQUENCE SEQ_IA NOCACHE;

CREATE SEQUENCE SEQ_HOUSE_NO NOCACHE;
CREATE SEQUENCE SEQ_PHOTO_NO NOCACHE;
CREATE SEQUENCE SEQ_REZ_NO NOCACHE;
CREATE SEQUENCE SEQ_REGION_NO NOCACHE;

CREATE SEQUENCE SEQ_REPORT_NO NOCACHE;
CREATE SEQUENCE SEQ_RAT_NO NOCACHE;

CREATE SEQUENCE SEQ_BNO NOCACHE;
CREATE SEQUENCE SEQ_BRE_NO NOCACHE;
CREATE SEQUENCE SEQ_BAT_NO NOCACHE;

CREATE SEQUENCE SEQ_FIND_NO NOCACHE;
CREATE SEQUENCE SEQ_FIND_REPLY_NO NOCACHE;
CREATE SEQUENCE SEQ_FATTACHMENT_NO NOCACHE;

CREATE SEQUENCE SEQ_PAYMENT_NO NOCACHE;

----------------- 회원 -----------------
CREATE TABLE MEMBER (
	"MEMBER_ID" VARCHAR2(15) PRIMARY KEY,
	"MEMBER_PWD" VARCHAR2(300) NOT NULL,
	"MEMBER_NAME" VARCHAR2(20) NOT NULL,
	"NICKNAME" VARCHAR2(60) NOT NULL UNIQUE,
	"PHONE" VARCHAR2(15) NOT NULL UNIQUE,
	"EMAIL" VARCHAR2(30) NOT NULL UNIQUE,
	"GENDER" CHAR(1) NOT NULL,
	"AREA" VARCHAR2(200),
	"BIRTH" VARCHAR2(8) NOT NULL,
	"ENROLL_DATE" DATE DEFAULT SYSDATE NOT NULL,
	"MODIFY_DATE" DATE DEFAULT SYSDATE NOT NULL,
	"LOGIN_DATE" DATE DEFAULT SYSDATE NOT NULL,
	"CHANGE_NAME" VARCHAR2(300),
	"EMAIL_VERIFY" NUMBER DEFAULT 0,
	"NAVERLOGIN" VARCHAR2(300),
	"MEMBER_COMMENT" VARCHAR2(300),
	"MEMBER_POINT" NUMBER DEFAULT 0,
	"STATUS" VARCHAR2(20) DEFAULT '일반' NOT NULL,
	LATITUDE NUMBER(9,6),
	LONGITUDE NUMBER(9,6)
		
);


CREATE TABLE MEMBER_AUTH(
    "MAIL_AUTH" NUMBER DEFAULT 0, 
	"MAIL_KEY" VARCHAR2(50), 
	"MAIL_DATE" DATE DEFAULT SYSDATE, 
	"EMAIL" VARCHAR2(30 BYTE) NOT NULL,
    "ADMIN_AUTH" NUMBER DEFAULT 0,
    FOREIGN KEY (EMAIL) REFERENCES MEMBER(EMAIL) ON DELETE CASCADE);

------------------자유게시판----------------------
CREATE TABLE BOARD (
  BOARD_NO     NUMBER PRIMARY KEY,
  BOARD_TITLE  VARCHAR2(300) NOT NULL,
  BOARD_CONTENT VARCHAR2(3000) NOT NULL,
  BOARD_VIEW   NUMBER        DEFAULT 0 NOT NULL,
  BOARD_DATE   DATE          DEFAULT SYSDATE NOT NULL,
  STATUS       CHAR(1)       DEFAULT 'Y' NOT NULL,
  MEMBER_ID    VARCHAR2(15)  NOT NULL,
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE
);
-------------------자유게시판 댓글-----------------
CREATE TABLE BOARD_REPLY (
	BRE_NO	NUMBER	PRIMARY KEY,
	BRE_CONTENT	VARCHAR2(300)		NOT NULL,
	BRE_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	STATUS	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	BOARD_NO	NUMBER		NOT NULL,
	BRE_ID	VARCHAR2(30)		NOT NULL,
FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE
);
------------------자유게시판 첨부파일---------------
CREATE TABLE BATTACHMENT (
	BAT_NO	NUMBER	PRIMARY KEY,
	ORIGIN_NAME	VARCHAR2(300)		NOT NULL,
	CHANGE_NAME	VARCHAR2(300)		NOT NULL,
	CREATE_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	FILE_STATUS	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	BOARD_NO	NUMBER		NOT NULL,
    FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE 
);
--------------------------------------------------
--------------        FIND	 ------------------	
--------------------------------------------------
CREATE TABLE FIND (
	FIND_NO	NUMBER PRIMARY KEY,
	FIND_TITLE	VARCHAR2(300)	NOT NULL,
	FIND_CONTENT	VARCHAR2(3000)	NOT NULL,
	FIND_CATEGORY	VARCHAR2(30)	NOT NULL,
	FIND_VIEW	NUMBER	DEFAULT 0	NOT NULL,
	FIND_DATE	DATE DEFAULT SYSDATE NOT NULL,
	STATUS	CHAR(1)	DEFAULT 'Y'	NOT NULL,
    MEMBER_ID VARCHAR2(15) NOT NULL,
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE
);
--------------------------------------------------
--------------     FIND REPLY	 ------------------	
--------------------------------------------------
CREATE TABLE FIND_REPLY (
	FRE_NO	NUMBER PRIMARY KEY,
	FRE_CONTENT	VARCHAR2(3000)	NOT NULL,
	FRE_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	STATUS	CHAR(1)	DEFAULT 'Y'	NOT NULL,
    FIND_NO NUMBER NOT NULL,
	FOREIGN KEY (FIND_NO) REFERENCES FIND(FIND_NO) ON DELETE CASCADE
);
--------------------------------------------------
--------------    FATTACHMENT  ------------------	
--------------------------------------------------
CREATE TABLE FATTACHMENT (
	FAT_NO	NUMBER PRIMARY KEY,
	ORIGIN_NAME	VARCHAR2(300)		NOT NULL,
	CHANGE_NAME	VARCHAR2(300)		NOT NULL,
	CREATE_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	FILE_LEVEL	NUMBER		NOT NULL,
	FILE_STATUS	CHAR(1)	DEFAULT 'Y'	NOT NULL,
    FIND_NO NUMBER NOT NULL,
	FOREIGN KEY (FIND_NO) REFERENCES FIND(FIND_NO) ON DELETE CASCADE
);

-- 쉐어하우스 테이블
CREATE TABLE HOUSE (
	HOUSE_NO	NUMBER	NOT NULL,
	HOUSE_NAME	VARCHAR2(50)		NOT NULL,
	HOUSE_ADDRESS	VARCHAR2(100)		NOT NULL,
	DEPOSIT	NUMBER	DEFAULT 0	NOT NULL,
	RENT	NUMBER	DEFAULT 0	NOT NULL,
	ENTER_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
   	MAX_ENTER_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	MIN_STAY	VARCHAR2(100)	DEFAULT '0일'	NOT NULL,
	MAX_STAY	VARCHAR2(100)	DEFAULT '0일'	NULL,
	ROOM_PEOPLE	NUMBER	DEFAULT 1	NOT NULL,
	INC_FURNITURE	VARCHAR2(400)		NULL,
	HOUSE_CONTENT VARCHAR2(400) NULL, 
	RES_GENDER	VARCHAR2(20)	DEFAULT '상관없음'	NOT NULL,
	RES_TYPE	VARCHAR2(20)		NULL,
	FLOOR	VARCHAR2(20)		NULL,
	HOUSE_STATUS	CHAR(1)	DEFAULT 'Y'	NOT NULL,
    ENROLL_STATUS VARCHAR2(15) DEFAULT '심사중' NOT NULL,
	HOUSE_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	MEMBER_ID	VARCHAR2(15)		NOT NULL,
	LATITUDE NUMBER(9,6),
	LONGITUDE NUMBER(9,6),
	AGE	NUMBER	DEFAULT 0	NOT NULL,
    PRIMARY KEY (HOUSE_NO),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE 
);


-- 사진 테이블 
CREATE TABLE PHOTO (
	PHOTO_NO	NUMBER	NOT NULL,
	ORIGIN_NAME	VARCHAR2(300)		NOT NULL,
    CHANGE_NAME	VARCHAR2(300)		NOT NULL,
	CREATE_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
    FILE_LEVEL CHAR(1)	NOT NULL,
	FILE_STATUS	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	HOUSE_NO	NUMBER		NOT NULL,
    PRIMARY KEY (PHOTO_NO),
    FOREIGN KEY (HOUSE_NO) REFERENCES HOUSE (HOUSE_NO) ON DELETE CASCADE 
);


-- 예약 테이블 
CREATE TABLE RESERVATION (
	REZ_NO	NUMBER	NOT NULL,
   	REZ_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
    REZ_HOUR    VARCHAR2(20) NOT NULL,
	SEND_MEMBER_ID	VARCHAR2(15)	NOT NULL,
 	REC_MEMBER_ID	VARCHAR2(15)	NOT NULL,
	REZ_STATUS	VARCHAR2(20)	DEFAULT '예약신청'	NOT NULL,
    REZ_REQUEST_DATE DATE DEFAULT SYSDATE NOT NULL,
    CANCEL_CONTENT VARCHAR2(200),
    DEL_STATUS CHAR(1) DEFAULT 'N' NOT NULL,
	HOUSE_NO	NUMBER		NOT NULL,
    PRIMARY KEY (REZ_NO),
    FOREIGN KEY (HOUSE_NO) REFERENCES HOUSE (HOUSE_NO) ON DELETE CASCADE 
);

-- 지역 테이블
CREATE TABLE REGION (
	REGION_NO	NUMBER	NOT NULL,
	REGION_NAME	VARCHAR2(300)		NULL,
	LATITUDE	NUMBER	DEFAULT 37.53390467755	NOT NULL,
	LONGITUDE	NUMBER	DEFAULT 126.89761233595	NOT NULL
);

CREATE TABLE CHAT_LIST (
    "CHAT_NO"     NUMBER        NOT NULL,
    "CUSER"     VARCHAR2(60)        NOT NULL,
    "MUSER"     VARCHAR2(60)        NOT NULL,
	"STATUS"     CHAR(1)        DEFAULT 'Y'	NOT NULL,
    "C_DATE"    TIMESTAMP(6)        DEFAULT SYSDATE    NOT NULL
);

ALTER TABLE CHAT_LIST ADD CONSTRAINT PK_CHAT_LIST PRIMARY KEY ("CHAT_NO");

CREATE TABLE CHAT_LOG (
    "SEND_USER"     VARCHAR2(60)        NOT NULL,
    "RECEIVE_USER"  VARCHAR2(60)        NOT NULL,
    "CONTENT"       VARCHAR2(500)       NOT NULL,
    "SEND_DATE"     TIMESTAMP(6) DEFAULT SYSDATE    NOT NULL,
    "CHAT_NO"         NUMBER        NOT NULL,
    "STATUS"        CHAR(1)    DEFAULT 'Y'    NOT NULL,
	"R_STATUS"        CHAR(1)    DEFAULT 'N'    NOT NULL
);

ALTER TABLE CHAT_LOG ADD CONSTRAINT FK_CHAT_NO FOREIGN KEY ("CHAT_NO")
REFERENCES "CHAT_LIST" ("CHAT_NO") ON DELETE CASCADE;


-- INREVIEW 테이블 생성
CREATE TABLE "INREVIEW" (
    "INR_NO"        NUMBER        NOT NULL,
    "INR_TITLE"     VARCHAR2(300)        NOT NULL,
    "INR_CONTENT"   VARCHAR2(3000)        NOT NULL,
    "INR_VIEW"      NUMBER    DEFAULT 0    NOT NULL,
    "INR_DATE"      DATE    DEFAULT SYSDATE    NOT NULL,
    "STATUS"        CHAR(1)    DEFAULT 'Y'    NOT NULL,
    "MEMBER_ID"     VARCHAR2(15)        NOT NULL
);

-- INREVIEW 테이블의 기본키 설정
ALTER TABLE "INREVIEW" ADD CONSTRAINT PK_INREVIEW PRIMARY KEY ("INR_NO");

-- IATTACHMENT 테이블 생성
CREATE TABLE "IATTACHMENT" (
    "FILE_NO"       NUMBER        NOT NULL,
    "ORIGIN_NAME"   VARCHAR2(300)        NOT NULL,
    "CHANGE_NAME"   VARCHAR2(300)        NOT NULL,
    "FILE_LEVEL"    NUMBER,
    "CREATE_DATE"   DATE    DEFAULT SYSDATE    NOT NULL,
    "FILE_STATUS"   CHAR(1)    DEFAULT 'Y'    NOT NULL,
    "INR_NO"        NUMBER        NOT NULL
);

-- IATTACHMENT 테이블의 기본키 설정
ALTER TABLE "IATTACHMENT" ADD CONSTRAINT PK_IATTACHMENT PRIMARY KEY ("FILE_NO");

-- INREVIEW 테이블의 외래키 설정
ALTER TABLE "INREVIEW" ADD CONSTRAINT FK_INR_MEMBER_ID FOREIGN KEY ("MEMBER_ID")
REFERENCES "MEMBER" ("MEMBER_ID") ON DELETE CASCADE;

-- IATTACHMENT 테이블의 외래키 설정
ALTER TABLE "IATTACHMENT" ADD CONSTRAINT FK_IA_INR_NO FOREIGN KEY ("INR_NO")
REFERENCES "INREVIEW" ("INR_NO") ON DELETE CASCADE;

CREATE TABLE "NOTICE" (
	"NOTICE_NO"	NUMBER	NOT NULL,
	"NOTICE_TITLE"	VARCHAR2(300)		NOT NULL,
	"NOTICE_CONTENT"	VARCHAR2(3000)		NOT NULL,
	"NOTICE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"NOTICE_VIEW"	NUMBER	DEFAULT 0	NOT NULL,
	"NOTICE_STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL
);
COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS '시퀀스로 채번';
ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_NO"
);


-- 공지사항 첨부 파일 --
CREATE TABLE "NATTACHMENT" (
	"NAT_NO"	NUMBER	NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(300)		NOT NULL,
	"CHANGE_NAME"	VARCHAR2(300)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"FILE_STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	"NOTICE_NO"	NUMBER	NOT NULL, FOREIGN KEY (NOTICE_NO) REFERENCES NOTICE(NOTICE_NO) ON DELETE CASCADE
);
COMMENT ON COLUMN "NATTACHMENT"."NOTICE_NO" IS '시퀀스로 채번';
ALTER TABLE "NATTACHMENT" ADD CONSTRAINT "PK_NAT_NO" PRIMARY KEY (
	"NAT_NO"
);
-- 이벤트 --
CREATE TABLE "EVENT" (
	"EVENT_NO"	NUMBER		NOT NULL,
	"EVENT_TITLE"	VARCHAR2(300)		NOT NULL,
	"EVENT_CATEGORY" VARCHAR2(100) 		NOT NULL,
	"EVENT_CONTENT"	VARCHAR2(3000)		NOT NULL,
	"EVENT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"EVENT_VIEW"	NUMBER	DEFAULT 0	NOT NULL,
	"EVENT_STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL
);
COMMENT ON COLUMN "EVENT"."EVENT_NO" IS '시퀀스로 채번';
ALTER TABLE "EVENT" ADD CONSTRAINT "PK_EVENT" PRIMARY KEY (
	"EVENT_NO"
);
-- 이벤트 파일 --

CREATE TABLE "EATTACHMENT" (
	"EAT_NO"	NUMBER	NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(300)		NOT NULL,
	"CHANGE_NAME"	VARCHAR2(300)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"FILE_STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	EVENT_NO	NUMBER	NOT NULL,
    FOREIGN KEY (EVENT_NO) REFERENCES EVENT(EVENT_NO) ON DELETE CASCADE
);
COMMENT ON COLUMN "EATTACHMENT"."EVENT_NO" IS '시퀀스로 채번';
ALTER TABLE "EATTACHMENT" ADD CONSTRAINT "PK_EAT_NO" PRIMARY KEY (
	"EAT_NO"
);
----------------- 찜목록 -----------------
CREATE TABLE WISH (
	"MEMBER_ID"	VARCHAR2(15)	NOT NULL,
	"HOUSE_NO"	NUMBER		NOT NULL,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
    FOREIGN KEY (HOUSE_NO) REFERENCES HOUSE(HOUSE_NO) ON DELETE CASCADE
);

----------------- 신고 -----------------
CREATE TABLE REPORT (
	REPORT_NO	NUMBER PRIMARY KEY,
	REPORT_TITLE	VARCHAR2(300)		NOT NULL,
	REPORT_CONTENT	VARCHAR2(3000)		NOT NULL,
	REPORT_TYPE	VARCHAR2(30)		NOT NULL,
	REPORT_ID	VARCHAR2(15)		NOT NULL,
	REPORT_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	REPORT_STATUS	VARCHAR2(30)	DEFAULT 'W'	NOT NULL,
	MEMBER_ID	VARCHAR2(15)		NOT NULL,
	TYPE_NO		NUMBER				NOT NULL
);
---------------------신고 첨부파일 -----------------
CREATE TABLE RATTACHMENT (
	RAT_NO	NUMBER	PRIMARY KEY,
	ORIGIN_NAME	VARCHAR2(300)		NOT NULL,
	CHANGE_NAME	VARCHAR2(300)		NOT NULL,
	CREATE_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	FILE_STATUS	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	REPORT_NO	NUMBER NOT NULL,
    FOREIGN KEY (REPORT_NO) REFERENCES REPORT(REPORT_NO) ON DELETE CASCADE

);

-------------- 알림 ---------------

CREATE TABLE NOTIFICATION (
  NO NUMBER PRIMARY KEY,
  CONTENT VARCHAR2(255),
  RECEIVER_ID VARCHAR2(15),
  SENDER_ID VARCHAR2(15),
  POST_NO NUMBER,
  POST_TYPE VARCHAR2(50),
  POST_CONTENT VARCHAR2(300),
  CREATED_TIME DATE DEFAULT SYSDATE

);
-- 결제 --
CREATE TABLE PAYMENT (
    PAYMENT_NO  NUMBER  NOT NULL,
    TID VARCHAR2(255)      NOT NULL,
    PRICE   VARCHAR2(255)      NOT NULL,
    PAYMENT_DATE    DATE    DEFAULT SYSDATE NOT NULL,
    PAYMENT_STATUS  VARCHAR2(30)    DEFAULT 'Y' NOT NULL,
    MEMBER_ID  VARCHAR2(30),
    HOUSE_NO    NUMBER      NOT NULL,
    PRIMARY KEY (PAYMENT_NO),
    FOREIGN KEY (HOUSE_NO) REFERENCES HOUSE (HOUSE_NO) ON DELETE CASCADE,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

CREATE SEQUENCE SEQ_NOTIFICATION_NO
NOCACHE;
